# Generated by Django 5.2.8 on 2025-12-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitticket',
            name='call_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitticket',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitticket',
            name='status',
            field=models.CharField(choices=[('WAITING', '候診'), ('CALLING', '叫號中'), ('IN_ROOM', '看診中'), ('DONE', '完成'), ('NO_SHOW', '未到')], default='WAITING', max_length=20),
        ),
    ]
