# Generated by Django 5.2.8 on 2025-12-02 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='藥品代碼')),
                ('name', models.CharField(max_length=100, verbose_name='藥品名稱')),
                ('generic_name', models.CharField(blank=True, max_length=100, verbose_name='學名 / 成分')),
                ('form', models.CharField(blank=True, max_length=50, verbose_name='劑型')),
                ('strength', models.CharField(blank=True, max_length=50, verbose_name='規格')),
                ('unit', models.CharField(default='顆', max_length=20, verbose_name='單位')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='目前庫存量')),
                ('reorder_level', models.PositiveIntegerField(default=0, verbose_name='安全存量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '藥品',
                'verbose_name_plural': '藥品',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(verbose_name='異動數量')),
                ('reason', models.CharField(choices=[('purchase', '進貨'), ('dispense', '發藥'), ('adjust', '手動調整')], max_length=20, verbose_name='原因')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.drug')),
            ],
            options={
                'verbose_name': '庫存異動',
                'verbose_name_plural': '庫存異動',
            },
        ),
    ]
