# Generated by Django 5.2.8 on 2025-11-14 05:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='代碼')),
                ('name', models.CharField(max_length=200, verbose_name='品名')),
                ('unit', models.CharField(default='TAB', max_length=20, verbose_name='單位')),
                ('stock', models.IntegerField(default=0, verbose_name='庫存')),
                ('lot_no', models.CharField(blank=True, max_length=50, verbose_name='批號')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='效期')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttype', models.CharField(choices=[('IN', '入庫'), ('OUT', '出庫')], max_length=3)),
                ('qty', models.IntegerField()),
                ('ref', models.CharField(blank=True, max_length=100, verbose_name='參考')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.drug')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
