# Generated by Django 5.2.8 on 2025-11-29 16:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('prescriptions', '0002_prescription_notes_prescriptionitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'verbose_name': '藥品', 'verbose_name_plural': '藥品'},
        ),
        migrations.RemoveField(
            model_name='drug',
            name='stock',
        ),
        migrations.AddField(
            model_name='drug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 29, 16, 8, 36, 812556, tzinfo=datetime.timezone.utc), verbose_name='建立時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='form',
            field=models.CharField(blank=True, max_length=50, verbose_name='劑型'),
        ),
        migrations.AddField(
            model_name='drug',
            name='generic_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='學名 / 成分'),
        ),
        migrations.AddField(
            model_name='drug',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0, verbose_name='安全存量'),
        ),
        migrations.AddField(
            model_name='drug',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='目前庫存量'),
        ),
        migrations.AddField(
            model_name='drug',
            name='strength',
            field=models.CharField(blank=True, max_length=50, verbose_name='規格'),
        ),
        migrations.AddField(
            model_name='drug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='藥品代碼'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='lot_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='批號'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=100, verbose_name='藥品名稱'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='unit',
            field=models.CharField(default='顆', max_length=20, verbose_name='單位'),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(verbose_name='異動數量')),
                ('reason', models.CharField(choices=[('purchase', '進貨'), ('dispense', '發藥'), ('adjust', '手動調整')], max_length=20, verbose_name='原因')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.drug')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': '庫存異動',
                'verbose_name_plural': '庫存異動',
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
