# Generated by Django 5.2.8 on 2025-11-30 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_drug_options_remove_drug_stock_drug_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-created_at'], 'verbose_name': '庫存紀錄', 'verbose_name_plural': '庫存紀錄'},
        ),
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='change',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='lot_no',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='note',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='prescription',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='ttype',
            field=models.CharField(choices=[('IN', '入庫 / 採購'), ('OUT', '出庫 / 調劑'), ('ADJ', '庫存調整')], default='IN', max_length=10, verbose_name='異動類型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='reorder_level',
            field=models.PositiveIntegerField(default=20, verbose_name='安全存量'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.drug'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='原因 / 備註'),
        ),
    ]
