# Generated by Django 5.2.8 on 2025-12-04 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_drug_unit_price'),
        ('prescriptions', '0005_alter_prescription_dispensed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='prescriptions.prescription', verbose_name='操作人員'),
        ),
    ]
