# Generated by Django 5.2.8 on 2025-12-04 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stocktransaction_prescription'),
        ('prescriptions', '0005_alter_prescription_dispensed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人員'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='prescriptions.prescription', verbose_name='相關處方'),
        ),
    ]
