# Generated by Django 5.2.8 on 2025-12-10 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stocktransaction_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.drug', verbose_name='藥品'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='reason',
            field=models.CharField(choices=[('purchase', '進貨'), ('dispense', '發藥'), ('return', '退藥'), ('adjust', '手動調整')], max_length=20, verbose_name='原因'),
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='批號')),
                ('expiry_date', models.DateField(verbose_name='有效期限')),
                ('quantity', models.PositiveIntegerField(verbose_name='目前庫存量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.drug', verbose_name='藥品')),
            ],
            options={
                'verbose_name': '藥品批次',
                'verbose_name_plural': '藥品批次',
                'ordering': ['expiry_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.stockbatch', verbose_name='批次'),
        ),
    ]
