# Generated by Django 5.2.8 on 2025-12-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stocktransaction_drug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='destroy_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='銷毀原因'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='destroyed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='銷毀時間'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='status',
            field=models.CharField(choices=[('normal', '正常可用'), ('quarantine', '隔離/待處理'), ('destroyed', '已銷毀')], default='normal', max_length=20, verbose_name='批次狀態'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='reason',
            field=models.CharField(choices=[('purchase', '進貨'), ('dispense', '發藥'), ('return', '退藥'), ('adjust', '手動調整'), ('destroy', '報廢/銷毀')], max_length=20, verbose_name='原因'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(fields=('drug', 'batch_no'), name='uniq_drug_batch_no'),
        ),
    ]
