# Generated by Django 5.2.8 on 2025-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockbatch_destroy_reason_stockbatch_destroyed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='quarantine_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='quarantine_reason',
            field=models.CharField(blank=True, choices=[('packaging', '包裝異常'), ('temperature', '溫控異常'), ('recall', '疑似召回/批次問題'), ('source', '來源/文件不齊'), ('other', '其他')], default='', max_length=20),
        ),
    ]
