# Generated by Django 5.2.8 on 2025-12-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockbatch_quarantine_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='quarantine_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='隔離備註'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='quarantine_reason',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='隔離原因'),
        ),
    ]
