# Generated by Django 5.2.8 on 2025-11-14 05:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('NEW', '開立'), ('READY', '待發藥'), ('DISPENSED', '已領藥')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=100, verbose_name='用法')),
                ('days', models.IntegerField(verbose_name='天數')),
                ('qty', models.IntegerField(verbose_name='數量')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
        ),
    ]
