# Generated by Django 5.2.8 on 2025-12-04 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_prescription_options_prescription_dispensed_at_and_more'),
        ('queues', '0002_visitticket_call_count_visitticket_is_skipped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='visit_ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='queues.visitticket'),
        ),
    ]
