# Generated by Django 5.2.8 on 2025-11-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_is_active'),
        ('inventory', '0002_alter_drug_options_remove_drug_stock_drug_created_at_and_more'),
        ('patients', '0002_alter_patient_chart_no'),
        ('prescriptions', '0002_prescription_notes_prescriptionitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='days',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='qty',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('final', '已確認')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='inventory.drug'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
