# Generated by Django 5.2.8 on 2025-12-04 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_alter_prescription_dispensed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '建立處方'), ('UPDATE', '修改處方'), ('DISPENSE', '完成領藥'), ('RETURN', '退藥'), ('CANCEL', '作廢')], max_length=20)),
                ('detail', models.TextField(blank=True, verbose_name='詳細紀錄')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人員')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='prescriptions.prescription', verbose_name='處方')),
            ],
            options={
                'verbose_name': '處方異動紀錄',
                'verbose_name_plural': '處方異動紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '建立處方'), ('update', '修改處方'), ('dispense', '藥局完成領藥'), ('cancel', '作廢處方'), ('return', '退藥並作廢')], max_length=20, verbose_name='動作')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='時間')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人員')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='prescriptions.prescription', verbose_name='處方')),
            ],
            options={
                'verbose_name': '處方異動紀錄',
                'verbose_name_plural': '處方異動紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
