# Generated by Django 5.2.8 on 2025-12-05 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_prescriptionauditlog_prescriptionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='審核時間'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='審核藥師'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='verify_note',
            field=models.TextField(blank=True, verbose_name='審核備註'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='verify_status',
            field=models.CharField(choices=[('PENDING', '待審核'), ('APPROVED', '已通過'), ('REJECTED', '已退回')], default='PENDING', max_length=20, verbose_name='審核狀態'),
        ),
    ]
