# Generated by Django 5.2.8 on 2025-12-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_prescription_verify_at_prescription_verify_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='pharmacy_status',
            field=models.CharField(choices=[('pending', '待領藥'), ('done', '已領藥'), ('cancelled', '已作廢')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='verify_note',
            field=models.TextField(blank=True, verbose_name='審核意見'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='verify_status',
            field=models.CharField(choices=[('pending', '待審核'), ('approved', '已通過'), ('rejected', '已退回'), ('query', '需澄清')], default='pending', max_length=20, verbose_name='審核狀態'),
        ),
    ]
