# Generated by Django 5.2.8 on 2025-12-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_alter_prescription_pharmacy_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='days_supply',
            field=models.PositiveIntegerField(default=7, verbose_name='療程天數'),
        ),
    ]
