# Generated by Django 5.2.8 on 2025-12-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0010_prescriptionitem_treatment_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='days_supply',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='treatment_days',
        ),
    ]
