# Generated by Django 5.2.8 on 2025-12-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0011_remove_prescriptionitem_days_supply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='days_supply',
            field=models.PositiveIntegerField(default=7, verbose_name='療程天數'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='treatment_days',
            field=models.PositiveIntegerField(default=1, help_text='例如連續吃幾天：1、3、7...  ', verbose_name='預計用藥天數'),
        ),
    ]
