# Generated by Django 5.2.8 on 2025-12-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('BOOKED', '已掛號'), ('CANCELLED', '已取消'), ('DONE', '已完成'), ('NO_SHOW', '未到 / 過號')], default='BOOKED', max_length=10),
        ),
    ]
