# Generated by Django 5.2.8 on 2025-12-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
        ('doctors', '0007_doctorleave'),
        ('patients', '0005_patient_other_risk_notes'),
    ]

    operations = [

    ]
