# Generated by Django 5.2.8 on 2026-01-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_uniq_patient_doctor_date_period'),
        ('doctors', '0008_alter_doctorschedule_session'),
        ('patients', '0005_patient_other_risk_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('doctor', 'date', 'time'), name='uniq_active_doctor_date_time'),
        ),
    ]
