# Generated by Django 5.2.8 on 2025-12-14 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0005_alter_doctorschedule_slot_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('level', models.CharField(choices=[('info', '資訊公告'), ('notice', '提醒公告'), ('block', '管制公告')], default='info', max_length=10, verbose_name='公告類型')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置頂')),
                ('show_on_homepage', models.BooleanField(default=True, verbose_name='顯示於首頁')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='醫院名稱')),
                ('description', models.TextField(blank=True, verbose_name='簡介')),
                ('phone', models.CharField(max_length=20, verbose_name='聯絡電話')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('opening_hours', models.TextField(help_text='例如：週一至週五 08:30-12:00 / 13:30-17:00', verbose_name='門診時間')),
                ('map_url', models.URLField(blank=True, verbose_name='地圖連結')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('period', models.CharField(choices=[('AM', '上午'), ('PM', '下午'), ('FULL', '全天')], max_length=10, verbose_name='請假時段')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctors.doctor', verbose_name='醫師')),
            ],
        ),
    ]
