# Generated by Django 5.2.8 on 2025-12-14 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctorleave'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, verbose_name='科別')),
                ('date', models.DateField(verbose_name='日期')),
                ('period', models.CharField(choices=[('AM', '上午'), ('PM', '下午')], max_length=2, verbose_name='時段')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('national_id', models.CharField(max_length=10, verbose_name='身分證字號')),
                ('birth_date', models.DateField(verbose_name='生日')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('status', models.CharField(choices=[('PENDING', '待審核'), ('APPROVED', '已核准'), ('REJECTED', '已駁回')], default='PENDING', max_length=10, verbose_name='狀態')),
                ('reject_reason', models.CharField(blank=True, max_length=200, verbose_name='駁回原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審核時間')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.doctor', verbose_name='醫師')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='DoctorLeave',
        ),
        migrations.AddIndex(
            model_name='publicregistrationrequest',
            index=models.Index(fields=['status', 'date', 'doctor'], name='public_publ_status_bc9c0c_idx'),
        ),
    ]
