# Generated by Django 5.2.8 on 2025-12-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_uniq_patient_doctor_date_period'),
        ('public', '0002_publicregistrationrequest_delete_doctorleave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicregistrationrequest',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_requests', to='appointments.appointment', verbose_name='建立的正式掛號'),
        ),
        migrations.AddField(
            model_name='publicregistrationrequest',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='時間'),
        ),
    ]
