# Generated by Django 5.2.8 on 2025-11-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='身分證')),
                ('nhi_no', models.CharField(blank=True, max_length=20, verbose_name='健保卡號')),
                ('birth_date', models.DateField(verbose_name='生日')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('chart_no', models.CharField(max_length=20, unique=True, verbose_name='病歷號')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
            ],
        ),
    ]
