# Generated by Django 5.2.8 on 2025-11-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='chart_no',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='病歷號'),
        ),
    ]
