# Generated by Django 5.2.8 on 2025-12-07 23:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_chart_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['chart_no'], 'verbose_name': '病人', 'verbose_name_plural': '病人'},
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='例如：藥物過敏、食物過敏等', verbose_name='過敏史'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A 型'), ('B', 'B 型'), ('AB', 'AB 型'), ('O', 'O 型'), ('UNK', '未知')], default='UNK', max_length=3, verbose_name='血型'),
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True, help_text='例如：高血壓、糖尿病、心臟病等', verbose_name='慢性疾病 / 重要病史'),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='緊急聯絡人姓名'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='緊急聯絡人電話'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, help_text='例如：父、母、配偶、子女、朋友', max_length=50, verbose_name='與病人關係'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他 / 不透露')], max_length=1, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='patient',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='身高（cm）'),
        ),
        migrations.AddField(
            model_name='patient',
            name='note',
            field=models.TextField(blank=True, verbose_name='其他備註'),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='體重（kg）'),
        ),
    ]
