# Generated by Django 5.2.8 on 2025-12-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_options_patient_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='family_disease_notes',
            field=models.TextField(blank=True, help_text='例如：父母高血壓、糖尿病、遺傳疾病等', null=True, verbose_name='家族病史'),
        ),
    ]
