# Generated by Django 5.2.8 on 2025-12-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_family_disease_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='other_risk_notes',
            field=models.TextField(blank=True, null=True, verbose_name='其他風險備註'),
        ),
    ]
