# Generated by Django 5.2.8 on 2025-11-18 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': '醫師', 'verbose_name_plural': '醫師'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'verbose_name': '醫師門診班表', 'verbose_name_plural': '醫師門診班表'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='room_no',
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='room',
            field=models.CharField(blank=True, max_length=20, verbose_name='診間'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟用'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='max_patients',
            field=models.PositiveIntegerField(default=20, verbose_name='每診最多看診人數'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='session',
            field=models.CharField(choices=[('AM', '上午門診（09:00–12:00）'), ('PM', '下午門診（14:00–17:00）')], default='morning', max_length=2, verbose_name='時段'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用者帳號'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor', verbose_name='醫師'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='slot_minutes',
            field=models.PositiveIntegerField(default=20, verbose_name='每位看診間隔（分鐘）'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='weekday',
            field=models.IntegerField(choices=[(0, '星期一'), (1, '星期二'), (2, '星期三'), (3, '星期四'), (4, '星期五'), (5, '星期六'), (6, '星期日')], verbose_name='星期'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'weekday', 'session')},
        ),
    ]
