# Generated by Django 5.2.8 on 2025-11-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_options_alter_doctorschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟用'),
        ),
    ]
