# Generated by Django 5.2.8 on 2025-12-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='session',
            field=models.CharField(choices=[('AM', '上午門診（09:00–12:00）'), ('PM', '下午門診（14:00–17:00）'), ('PM', '下午門診（18:00–23:00）')], max_length=2, verbose_name='時段'),
        ),
    ]
