# Generated by Django 5.2.8 on 2025-12-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctorschedule_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='slot_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='每位看診間隔（分鐘）'),
        ),
    ]
