# Generated by Django 5.2.8 on 2025-12-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctorschedule_slot_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='科別'),
        ),
    ]
