# Generated by Django 5.2.8 on 2025-12-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='請假開始日')),
                ('end_date', models.DateField(verbose_name='請假結束日')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='原因')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctors.doctor')),
            ],
            options={
                'ordering': ('-start_date', '-end_date', 'doctor_id'),
                'indexes': [models.Index(fields=['doctor', 'start_date', 'end_date'], name='doctors_doc_doctor__15dbad_idx')],
            },
        ),
    ]
