# Generated by Django 5.2.8 on 2026-01-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctorleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='session',
            field=models.CharField(choices=[('AM', '上午門診（09:00–12:00）'), ('PM', '下午門診（14:00–17:00）')], max_length=2, verbose_name='時段'),
        ),
    ]
